[build-system]
requires = ["setuptools >= 80"]
build-backend = "setuptools.build_meta"

[project]
name = "rotlib"
#version = "1.0" #
dynamic = ["version"]
authors = [
  { name="Sarit Dutta", email="saridut@gmail.com" },
]
description = "Interconversion between rotation representations."
#readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = ["numpy >= 2.0.0"]

[project.urls]
#repository = "https://github.com/saridut/spam.git"
#download = 

[tool.setuptools.packages.find]
where = ["."]
include = ["rotlib*"]
exclude = ["./test*", "./docs*"]
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)


[tool.setuptools.dynamic]
version = {attr = "rotlib.__version__"} 

[tool.ruff]
line-length = 79
indent-width = 4

# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
# select = [...]  # See the Default Rules page for the full listing.
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

# If set to true, ignore missing documentation for *args and **kwargs parameters.
ignore-var-parameters = true

[tool.ruff.format]
quote-style = "double"

# Use the configured quote style for nested strings (Python 3.12+ only).
nested-string-quote-style = "preferred"

indent-style = "space"

# Respect magic trailing commas.
skip-magic-trailing-comma = false

# Automatically detect the appropriate line ending.
line-ending = "native"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.tox]
env_list = ["3.13", "3.12", "3.11", "3.10", "lint"]

[tool.tox.env_run_base]
description = "run the test suite with pytest"
deps = [
    "pytest >= 8",
    "numpy >= 2.0.0",
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[tool.tox.env.lint]
description = "run linters"
skip_install = true
deps = ["ruff"]
commands = [["ruff", "check", { replace = "posargs", default = ["."], extend = true }]]
